included:
  - URLRemote/Classes
line_length: 300
cyclomatic_complexity: 12
identifier_name:
  min_length: # not possible to disable this partial rule, so set it to zero
    warning: 0
    error: 0
disabled_rules:
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - todo
  - trailing_whitespace
  - type_body_length
