language: objective-c
osx_image: xcode8.2

branches:
  only:
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - brew update
  - brew install swiftlint || true
script:
  - swiftlint