language: objective-c
osx_image: xcode8.2

branches:
  only:
    - develop
    - master

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - brew update
  - brew install swiftlint || true
  - pod update
  - sudo gem update fastlane
  - cp ./URLRemote/Resources/mock-GoogleService-Info.plist ./URLRemote/Resources/GoogleService-Info.plist

script:
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then fastlane test; fi
  - swiftlint

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'URLRemote'
