update_fastlane
fastlane_version "2.27.0"
default_platform :ios

lane :test do
    scan(
        scheme: "URLRemote",
        device: "iPhone 7",
        clean: true,
        code_coverage: true
    )
end
